/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import concursoleiteiro.Vaca;
import concursoleiteiro.Concurso;
import java.awt.event.WindowEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matheus
 */
public class NovaVaca extends javax.swing.JFrame {

    private TabelaConcurso telaPassada;
    private Concurso conc;
    private float[] ordenhas;

    public NovaVaca() {
        initComponents();
        setDefaultCloseOperation(NovoConcurso.DISPOSE_ON_CLOSE);
    }

    public NovaVaca(TabelaConcurso tabConcurso, Concurso concurso) {
        initComponents();
        setDefaultCloseOperation(NovoConcurso.DISPOSE_ON_CLOSE);
        conc = concurso;

        /*int i;
        String[] strOrdenhas = new String[conc.getQtdOrdenhas()];
        for (i = 0; i < conc.getQtdOrdenhas(); i++) {
            comboBoxOrdenhas.addItem((i + 1) + "ª ordenha");
        }

        comboBoxOrdenhas = new JComboBox(strOrdenhas);
         */
        telaPassada = tabConcurso;
        ordenhas = new float[conc.getQtdOrdenhas()];

        criarTabela();
    }

    private void criarTabela() {
        DefaultTableModel model = (DefaultTableModel) tabelaOrdenhas.getModel();

        int i;
        for (i = 0; i < conc.getQtdOrdenhas(); i++) {
            model.addColumn((i + 1) + "ª ordenha");
        }
        model.setRowCount(1);

        tabelaOrdenhas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        produtorText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        municipioText = new javax.swing.JTextField();
        fazendaText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        percentualGorduraText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        nomeVacaText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaOrdenhas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Nova Vaca");

        jLabel2.setText("Produtor*");

        jLabel3.setText("Município*");

        jLabel4.setText("Fazenda*");

        jLabel11.setText("Percentual de Gordura");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nome da Vaca*");

        tabelaOrdenhas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaOrdenhas);

        jLabel7.setText("Ordenhas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(produtorText)
                    .addComponent(nomeVacaText)
                    .addComponent(municipioText)
                    .addComponent(fazendaText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(percentualGorduraText)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produtorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeVacaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(municipioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fazendaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentualGorduraText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!(produtorText.getText()).isEmpty() && !(nomeVacaText.getText()).isEmpty() && !(municipioText.getText()).isEmpty() && !(fazendaText.getText()).isEmpty()) {
            try {
                Vaca vaca = new Vaca();
                vaca.setProdutor(produtorText.getText());
                vaca.setNome(nomeVacaText.getText());
                vaca.setMunicipio(municipioText.getText());
                vaca.setFazenda(fazendaText.getText());

                if (!(percentualGorduraText.getText()).isEmpty()) {
                    vaca.setPerGordura(Float.valueOf(percentualGorduraText.getText()));
                }
                
                for (int i = 0; i < conc.getQtdOrdenhas(); i++){
                    ordenhas[i] = (float) Float.parseFloat(tabelaOrdenhas.getModel().getValueAt(0, i).toString());
                }
                
                vaca.setOrdenha(ordenhas);
                
                float total = 0;
                for (int i = 0; i < conc.getQtdOrdenhas(); i++) total += ordenhas[i];
                
                vaca.setTotal(total);
                vaca.setMedia(total/conc.getQtdOrdenhas());
                
                conc.adicionarVaca(vaca);
                conc.setQtdVacas(conc.getQtdVacas() + 1);

                telaPassada.refresh();
                
                this.dispose();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Por favor insira números na tabela.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Algum campo está vazio. Favor preenche-lo.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaVaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaVaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaVaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaVaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaVaca().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fazendaText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField municipioText;
    private javax.swing.JTextField nomeVacaText;
    private javax.swing.JTextField percentualGorduraText;
    private javax.swing.JTextField produtorText;
    private javax.swing.JTable tabelaOrdenhas;
    // End of variables declaration//GEN-END:variables
}
