/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import concursoleiteiro.Concurso;
import concursoleiteiro.Vaca;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author matheus
 */
public class TabelaConcurso extends javax.swing.JFrame {

    private Concurso conc;

    private TabelaConcurso() {
        initComponents();
    }

    public TabelaConcurso(Concurso concurso) {
        initComponents();
        textoId.setText(String.valueOf(concurso.getId()));
        textoData.setText(concurso.getData());
        textoLocalidade.setText(concurso.getLocalidade());

        concurso.criarListaVacas();
        concurso.setQtdVacas(0);
        conc = concurso;

        criarTabela();
    }

    private void criarTabela() {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        model.addColumn("Produtor");
        model.addColumn("Município");
        model.addColumn("Fazenda");
        model.addColumn("Nome da Vaca");

        int i;
        for (i = 0; i < conc.getQtdOrdenhas(); i++) {
            model.addColumn((i + 1) + "ª ordenha");
        }

        model.addColumn("Total");
        model.addColumn("Media");
        model.addColumn("Diferença");
        model.addColumn("Perc de Gordura");
        model.addColumn("Desvio Padrão");

        tabela.setModel(model);
    }
    
    void refresh(){
        TableModel model = tabela.getModel();
        for (int i = 0; i < conc.getQtdVacas(); i++) {
            Vaca vaca = conc.getVacas().get(i);
            
            model.setValueAt(vaca.getProdutor(), i, 0);
            model.setValueAt(vaca.getMunicipio(), i, 1);
            model.setValueAt(vaca.getFazenda(), i, 2);
            model.setValueAt(vaca.getNome(), i, 3);

            float[] ord = vaca.getOrdenha();
            int j;
            for (j = 0; j < conc.getQtdOrdenhas(); j++) {
                model.setValueAt(ord[j], i, j+4);
            }
            
            model.setValueAt(vaca.getTotal(), i, j+4);
            model.setValueAt(vaca.getMedia(), i, j+5);
            model.setValueAt(vaca.getDiferenca(), i, j+6);
            model.setValueAt(vaca.getPerGordura(), i, j+7);
            model.setValueAt(vaca.getDesvPadrao(), i, j+8);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoId = new javax.swing.JLabel();
        textoLocalidade = new javax.swing.JLabel();
        textoData = new javax.swing.JLabel();
        adicionarVacaButton = new javax.swing.JButton();
        alterarVacaButton = new javax.swing.JButton();
        excluirVacaButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel2.setText("Localidade:");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel3.setText("Data:");

        textoId.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        textoLocalidade.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        textoData.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        adicionarVacaButton.setText("Adicionar");
        adicionarVacaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarVacaButtonActionPerformed(evt);
            }
        });

        alterarVacaButton.setText("Alterar");

        excluirVacaButton.setText("Excluir");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel4.setText("Vacas");

        jButton4.setText("Salvar");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(adicionarVacaButton)
                        .addGap(18, 18, 18)
                        .addComponent(alterarVacaButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirVacaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoId)
                                .addGap(225, 225, 225)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoLocalidade)
                                .addGap(236, 236, 236)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoData))
                            .addComponent(jLabel4))
                        .addGap(0, 558, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adicionarVacaButton, alterarVacaButton, excluirVacaButton, jButton4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(textoId)
                    .addComponent(textoLocalidade)
                    .addComponent(textoData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarVacaButton)
                    .addComponent(alterarVacaButton)
                    .addComponent(excluirVacaButton)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarVacaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarVacaButtonActionPerformed
        NovaVaca frame = new NovaVaca(this, conc);
        frame.setVisible(true);
    }//GEN-LAST:event_adicionarVacaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaConcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaConcurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarVacaButton;
    private javax.swing.JButton alterarVacaButton;
    private javax.swing.JButton excluirVacaButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel textoData;
    private javax.swing.JLabel textoId;
    private javax.swing.JLabel textoLocalidade;
    // End of variables declaration//GEN-END:variables

}
